Dz5 modal done
js-tasks-ru/htmlcss-20210916_mvdmvn pull request #10
Opened 2021-09-29 20:07 UTC by MVDMVN

2021-09-29 20:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-29 20:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-30 09:50 UTC, GSemikozov requested changes

2021-09-30 09:50 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal {
это просто общая подложка для модалки? вспомогательные стили не относящиеся в блоку (а блок у нас это .modal-window) можно унести в тег style хтмл страницы с решением задачи

2021-09-30 09:50 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  background: #c4c4c4;
здесь важно использовать rgba (a - это альфа-канал через который можно указать полу-прозрачность). Соответственно ниже указывать opacity не надо (иначе все вложенные элементы тоже будут полупрозрачными)

2021-09-30 09:50 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
можно через absolute

2021-09-30 09:50 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal-wrapper {
скорректируем по БЭМ - .modal-window__wrapper

2021-09-30 09:50 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  color: #334d6e;
цвет по идее есть в main.css

2021-09-30 16:09 UTC, MVDMVN commented on 05-lection3/02-modal/modal.css
> +.modal {
Готово

2021-09-30 16:11 UTC, MVDMVN commented on 05-lection3/02-modal/modal.css
> +  background: #c4c4c4;
Готово

2021-09-30 16:11 UTC, MVDMVN commented on 05-lection3/02-modal/modal.css
> +.modal-wrapper {
Готово

2021-09-30 16:13 UTC, MVDMVN commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
В конце урока ты говорил, что нужно делать через fixed) Но готово

2021-09-30 16:13 UTC, MVDMVN commented on 05-lection3/02-modal/modal.css
> +  color: #334d6e;
Готово

2021-10-01 08:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
но это же враппер) а я имел в виду сам блок модалки - через fixed. Все что внутри - можно уже без fixed

2021-10-01 08:12 UTC, GSemikozov approved these changes

2021-10-01 08:13 UTC, merged