dz5_calendar done
js-tasks-ru/htmlcss-20210916_mvdmvn pull request #11
Opened 2021-09-30 05:57 UTC by MVDMVN

2021-09-30 05:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-30 09:52 UTC, GSemikozov requested changes

2021-09-30 09:52 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  color: #90a0b7;
здесь и ниже - цвета лучше забирать из переменных (если не определены еще - определить)

2021-09-30 16:05 UTC, MVDMVN commented on 05-lection3/03-calendar/calendar.css
> +  color: #90a0b7;
Готово

2021-09-30 16:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-30 16:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-30 16:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-01 08:13 UTC, GSemikozov approved these changes

2021-10-01 08:13 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-10-02 16:46 UTC, GSemikozov approved these changes

2021-10-02 16:46 UTC, merged