accordeon task
js-tasks-ru/htmlcss-20210916_mvdmvn pull request #4
Opened 2021-09-22 17:27 UTC by MVDMVN

2021-09-22 17:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 17:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-22 18:26 UTC, GSemikozov requested changes

2021-09-22 18:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordions {
по этому поводу см предыдущий ПР :)

2021-09-22 20:14 UTC, MVDMVN commented on 03-lection1/02-accordion/accordion.css
> +.accordions {
Готово

2021-09-23 16:35 UTC, GSemikozov approved these changes

2021-09-23 16:35 UTC, merged