Dz4 histogram
js-tasks-ru/htmlcss-20210916_mvdmvn pull request #6
Opened 2021-09-26 19:31 UTC by MVDMVN

2021-09-27 14:54 UTC, GSemikozov requested changes

2021-09-27 14:54 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +p {
какой-то глобальный стиль затесался среди стилей компонента)

2021-09-27 14:54 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin: 50px auto 0 auto;
внешнее позиционирование, в том числе марджины, на уровне блока низзя задавать в соответствии с БЭМ ;)

2021-09-27 14:54 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 150px;
высоту точно советую не фиксировать (на случай если тайтл будет в 2 строки или добавить еще какой-нибудь текст)

2021-09-27 14:54 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.head {
по БЭМ это должен быть элемент блока, то есть .head -> .histogram__head

2021-09-27 14:54 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.order-count__title {
отсюда и ниже - общая ошибка: элементы. описаны как элементы других блоков, а не histogram (.order-count, .link, .content). Если есть желание больше раздробить блок - на более мелкие блоки - тогда нужно создавать папки с отдельными файлами стилей для таких блоков. Если же мы хотим описывать элементы суть гистограммы - тогда нужно переписать классы в соответствии с БЭМ. Еще. раз - описываем элементы гистограммы, поэтому: .order-count__title -> .histogram__title (.histogram__order-count-title, c amount то же самое), .link__item -> .histogram__link, .content -> .histogram__chart,  .content__item -> .histogram__chart-item

2021-09-27 15:12 UTC, MVDMVN commented on 04-lection2/01-histogram/histogram.css
> +.order-count__title {
Готово

2021-09-27 15:12 UTC, MVDMVN commented on 04-lection2/01-histogram/histogram.css
> +.head {
Готово

2021-09-27 15:13 UTC, MVDMVN commented on 04-lection2/01-histogram/histogram.css
> +  height: 150px;
Готово

2021-09-27 15:13 UTC, MVDMVN commented on 04-lection2/01-histogram/histogram.css
> +  margin: 50px auto 0 auto;
Когда-то я научусь вспоминать про это до пул реквеста, готово)

2021-09-27 15:13 UTC, MVDMVN commented on 04-lection2/01-histogram/histogram.css
> +p {
Он быстро ретировался, готово

2021-09-28 08:00 UTC, GSemikozov requested changes

2021-09-28 08:00 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 50px;
еще про марджин сверху забыли)

2021-09-29 17:24 UTC, GSemikozov approved these changes

2021-09-29 17:24 UTC, merged