Dz4 main page cards
js-tasks-ru/htmlcss-20210916_mvdmvn pull request #8
Opened 2021-09-27 16:06 UTC by MVDMVN

2021-09-27 16:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-27 16:13 UTC, GSemikozov requested changes

2021-09-27 16:13 UTC, GSemikozov commented on components/main/main.css
> +.main__cards {
так не пойдет)
лучше создать компонент preview  и уже там задать отступ сверху и снизу, но - внутренний (паддинг).
затем у preview будет элемент в который мы и будем помещать карточки - preview__box (то что сейчас .cards). Кроме того, у preview__card будет только ширина определяться + марджин (.cards__item-main - этот класс лишний), остальное специфичное для карточки выносим в отдельный компонент .card

2021-09-28 05:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-28 05:36 UTC, MVDMVN commented on components/main/main.css
> +.main__cards {
Готово

2021-09-28 07:58 UTC, GSemikozov requested changes

2021-09-28 07:58 UTC, GSemikozov commented on index.html
> +            <div class="preview__card"></div>
чуть выше подключен файл card.css а здесь используется только элемент preview__card :) а, и еще не вижу самих добавлены стилей, может не закоммитились?)

2021-09-28 09:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-28 09:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 06:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 17:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 17:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 19:21 UTC, GSemikozov approved these changes

2021-09-29 19:21 UTC, merged